# Generated by Django 2.0.6 on 2018-06-10 06:09

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('address', models.CharField(max_length=30)),
                ('port', models.CharField(max_length=30)),
                ('read_amount', models.IntegerField()),
                ('write_amount', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
